CREATE INDEX M_DISCOUNT_I1 ON M_DISCOUNT (CUST_AN8,MCU_CODE,PG_ID,SINCE_JD,UNTIL_JD);
CREATE INDEX M_DISCOUNT_I2 ON M_DISCOUNT (CUST_AN8,MCU_CODE,ITEM_NO,SINCE_JD,UNTIL_JD);
CREATE INDEX M_DISCOUNT_I3 ON M_DISCOUNT (MCU_CODE,PG_ID,SINCE_JD,UNTIL_JD);
CREATE INDEX M_DISCOUNT_I4 ON M_DISCOUNT (MCU_CODE,ITEM_NO,SINCE_JD,UNTIL_JD);
