-- VL: CRPDTA@ERP
-- PD: PRODDTA

-- JULIAN DATE = select 100000+TO_CHAR(SYSDATE,'YYDDD') J from dual

-- 公司主数据（00开头是总公司，18开头是分公司）
-- 68 | M_CO
select
  CCUPMJ JD, CCUPMT JT, CCCO CODE
, CCNAME NAME, CCCRCD CUR_CODE
from CRPDTA.F0010@ERP

-- 分公司主数据
-- 60 | M_BP
select
  MCUPMJ JD, MCUPMT JT, MCAN8 AN8
, MCCO CO_CODE
, MCRP21 CODE, MCDC NAME
from CRPDTA.F0006@ERP
where MCSTYL='BP' and MCAN8>18000 and MCAN8<19000

-- 分公司仓库
-- 60 | M_BP_MCU
select
  MCUPMJ JD, MCUPMT JT, MCAN8 AN8
, MCRP21 BP_CODE, MCCO CO_CODE
, MCMCU CODE, MCDL01 NAME, MCDC ABBR
from CRPDTA.F0006@ERP
where MCSTYL='BP' and MCAN8>180000 and MCAN8<190000

-- 分公司电话
-- 104 | M_BP_TEL
select
  WPUPMJ JD, WPUPMT JT, WPAN8 BP_AN8, WPRCK7 SEQ
, WPAR1 TEL_AREA, WPPH1 TEL
from CRPDTA.F0115@ERP
where WPAN8 > 18000 and WPAN8 < 19000
and WPPHTP in ('TEL','WE')

-- 员工主数据
-- 1666 | M_EMP
select
  ABUPMJ JD, ABUPMT JT, ABAN8 AN8
, ABALPH NAME
from CRPDTA.F0101@ERP
where ABAT1='E'

-- 员工手机、邮箱
-- 没有维护有效数据 | M_EMP_PHONE_EMAIL
select
  WPAN8 EMP_AN8, WPRCK7 SEQ
, WPPHTP CTG, WPPH1 VAL
from CRPDTA.F0115@ERP
where WPAN8 > 50000000 and WPAN8 < 60000000
and WPPHTP in ('PH','MAIL')

------------------------------------------------------------------------

-- 25140 | M_CUST
select
  JDE_UPMJ JD, JDE_UPMT JT, ID AN8
, JDE_VALID_FROM SINCE_JD, JDE_VALID_TO UNTIL_JD
, ORGID BP_AN8, JDE_E58RCI2 MCU_AN8, AGENT_ID EMP_AN8, CUST_NAME NAME, CUST_SOURCE SRC
, JDE_E58HPROC ADDR_PROV, JDE_E58HCITY ADDR_CITY, JDE_E58HPREF ADDR_PREF, JDE_E58HXXDZ ADDR_MORE
, JDE_E58MBLC PTC, JDE_PH1 PHONE, JDE_E58HMAIL EMAIL, JDE_E58HSHDH TEL
, TXAL TAX_CODE, CRCD CUR_CODE
from TPPLATVL.TDP_CUST@ERP

-- 内销产品主数据
-- 24262 | M_ITEM
select
  IMUPMJ JD, IMITM NO
, IMLITM CODE, IMDSC1 NAME
, IMPRP1 C1, IMPRP2 C2, IMSRP2 C3, IMPRGR PG
, IMLNTY LINE_TYPE, IMSTKT INV_STATUS
, IMDSC2 SPEC, IMSRP0 MATERIAL, IMSRP9 TEETH
, STDL02 BRAND, STAA10 GRADE, STDSC1 TREAT, STDSC2 STD
, STAA14 DIM, 0 DIM_VAL, '' LEN, 0 LEN_VAL
, IMAITM CODE_OLD/*逻辑无关属性*/
from CRPDTA.F4101@ERP
left join CRPDTA.FE64101@ERP/*产品扩展属性，没有更新时间无法单独同步*/ on STITM=IMITM@ERP
where IMGLPT='IN01'/*内销产品*/

-- 产品英文名
-- 13373 | M_ITEM_EN
select
  IMUPMJ JD, IMITM ITEM_NO
, IMDSC1 NAME
from CRPDTA.F4101D@ERP

-- 转化至主计量单位的数量放大系数表
-- 17199 | M_UOM_XX2EA
select
  UMUPMJ JD, UMITM ITEM_NO, UMUM XX
, UMCONV EA_M7
from CRPDTA.F41002@ERP
where UMRUM='EA'

-- 主计量单位的重量（单位：KG/10^7）
-- 32743 | M_UOM_EA2KG
select
  UMUPMJ JD, UMITM ITEM_NO
, UMCONV KG_D7
from CRPDTA.F41002@ERP
where UMUM='EA' and UMRUM='KG'


-- 面价主数据(Sale Base Price)
-- 18714 | M_BASE_PRICE
select
  FPUPMJ JD, FPUPMT JT, FPITM ITEM_NO
, FPEFTJ SINCE_JD, FPEXDJ UNTIL_JD
, FPPRRC PRICE_D4
from CRPDTA.FE64201@ERP
where FPKY='01'/*一般国内面价*/
-- and 117224/*today*/ between FPEFTJ and FPEXDJ

-- 价格组配置表
-- 408 | M_PG
select
  IKIGID ID
, IKPRGR PG
from CRPDTA.F40941@ERP
-- select DRKY PG, DRDL01 PG_DESC from PRODCTL.F0005 where DRSY='40' and DRRT='PI';

-- 折扣主数据
-- 1451385 | M_DISCOUNT
-- 
-- 使用方式
-- 按以下顺序执行搜索（且 order by UNTIL_J asc, J desc, T desc），直到找到一条数据。
-- 1. 客户(CUST_AN8)+仓库(MCU_CODE)+料号(ITEM_NO)
-- 2. 客户(CUST_AN8)+仓库(MCU_CODE)+价格组(ITEM_PG_ID)
-- 3. 仓库(MCU_CODE)+料号(ITEM_NO)
-- 4. 仓库(MCU_CODE)+价格组(ITEM_PG_ID)
-- 
select
  BPUPMJ JD, BPTDAY JT
, BPAN8 CUST_AN8, BPMCU MCU_CODE, BPITM ITEM_NO, BPIGID ITEM_PG_ID
-- , BPCRCD CUR_CODE, BPUOM UOM_CODE -- 目前逻辑无关
, BPEFTJ SINCE_JD, BPEXDJ UNTIL_JD
, BPUPRC DISC_D4
from CRPDTA.F4106@ERP
-- where 117224/*today*/ between BPEFTJ and BPEXDJ
