TRUNCATE TABLE M_LOGISTIC;
INSERT INTO M_LOGISTIC (CODE,NAME)
SELECT 'AJ','安捷快递' FROM DUAL
UNION ALL SELECT 'ANE','安能物流' FROM DUAL
UNION ALL SELECT 'AXD','安信达快递' FROM DUAL
UNION ALL SELECT 'BQXHM','北青小红帽' FROM DUAL
UNION ALL SELECT 'BFDF','百福东方' FROM DUAL
UNION ALL SELECT 'BTWL','百世快运' FROM DUAL
UNION ALL SELECT 'CCES','CCES快递' FROM DUAL
UNION ALL SELECT 'CITY100','城市100' FROM DUAL
UNION ALL SELECT 'COE','COE东方快递' FROM DUAL
UNION ALL SELECT 'CSCY','长沙创一' FROM DUAL
UNION ALL SELECT 'CDSTKY','成都善途速运' FROM DUAL
UNION ALL SELECT 'DBL','德邦' FROM DUAL
UNION ALL SELECT 'DSWL','D速物流' FROM DUAL
UNION ALL SELECT 'DTWL','大田物流' FROM DUAL
UNION ALL SELECT 'EMS','EMS' FROM DUAL
UNION ALL SELECT 'FAST','快捷速递' FROM DUAL
UNION ALL SELECT 'FEDEX','FEDEX联邦(国内件）' FROM DUAL
UNION ALL SELECT 'FEDEX_GJ','FEDEX联邦(国际件）' FROM DUAL
UNION ALL SELECT 'FKD','飞康达' FROM DUAL
UNION ALL SELECT 'GDEMS','广东邮政' FROM DUAL
UNION ALL SELECT 'GSD','共速达' FROM DUAL
UNION ALL SELECT 'GTO','国通快递' FROM DUAL
UNION ALL SELECT 'GTSD','高铁速递' FROM DUAL
UNION ALL SELECT 'HFWL','汇丰物流' FROM DUAL
UNION ALL SELECT 'HHTT','天天快递' FROM DUAL
UNION ALL SELECT 'HLWL','恒路物流' FROM DUAL
UNION ALL SELECT 'HOAU','天地华宇' FROM DUAL
UNION ALL SELECT 'hq568','华强物流' FROM DUAL
UNION ALL SELECT 'HTKY','百世快递' FROM DUAL
UNION ALL SELECT 'HXLWL','华夏龙物流' FROM DUAL
UNION ALL SELECT 'HYLSD','好来运快递' FROM DUAL
UNION ALL SELECT 'JGSD','京广速递' FROM DUAL
UNION ALL SELECT 'JIUYE','九曳供应链' FROM DUAL
UNION ALL SELECT 'JJKY','佳吉快运' FROM DUAL
UNION ALL SELECT 'JLDT','嘉里物流' FROM DUAL
UNION ALL SELECT 'JTKD','捷特快递' FROM DUAL
UNION ALL SELECT 'JXD','急先达' FROM DUAL
UNION ALL SELECT 'JYKD','晋越快递' FROM DUAL
UNION ALL SELECT 'JYM','加运美' FROM DUAL
UNION ALL SELECT 'JYWL','佳怡物流' FROM DUAL
UNION ALL SELECT 'KYWL','跨越物流' FROM DUAL
UNION ALL SELECT 'LB','龙邦快递' FROM DUAL
UNION ALL SELECT 'LHT','联昊通速递' FROM DUAL
UNION ALL SELECT 'MHKD','民航快递' FROM DUAL
UNION ALL SELECT 'MLWL','明亮物流' FROM DUAL
UNION ALL SELECT 'NEDA','能达速递' FROM DUAL
UNION ALL SELECT 'PADTF','平安达腾飞快递' FROM DUAL
UNION ALL SELECT 'QCKD','全晨快递' FROM DUAL
UNION ALL SELECT 'QFKD','全峰快递' FROM DUAL
UNION ALL SELECT 'QRT','全日通快递' FROM DUAL
UNION ALL SELECT 'RFD','如风达' FROM DUAL
UNION ALL SELECT 'SAD','赛澳递' FROM DUAL
UNION ALL SELECT 'SAWL','圣安物流' FROM DUAL
UNION ALL SELECT 'SBWL','盛邦物流' FROM DUAL
UNION ALL SELECT 'SDWL','上大物流' FROM DUAL
UNION ALL SELECT 'SF','顺丰快递' FROM DUAL
UNION ALL SELECT 'SFWL','盛丰物流' FROM DUAL
UNION ALL SELECT 'SHWL','盛辉物流' FROM DUAL
UNION ALL SELECT 'ST','速通物流' FROM DUAL
UNION ALL SELECT 'STO','申通快递' FROM DUAL
UNION ALL SELECT 'STWL','速腾快递' FROM DUAL
UNION ALL SELECT 'SURE','速尔快递' FROM DUAL
UNION ALL SELECT 'TSSTO','唐山申通' FROM DUAL
UNION ALL SELECT 'UAPEX','全一快递' FROM DUAL
UNION ALL SELECT 'UC','优速快递' FROM DUAL
UNION ALL SELECT 'WJWL','万家物流' FROM DUAL
UNION ALL SELECT 'WXWL','万象物流' FROM DUAL
UNION ALL SELECT 'XBWL','新邦物流' FROM DUAL
UNION ALL SELECT 'XFEX','信丰快递' FROM DUAL
UNION ALL SELECT 'XYT','希优特' FROM DUAL
UNION ALL SELECT 'XJ','新杰物流' FROM DUAL
UNION ALL SELECT 'YADEX','源安达快递' FROM DUAL
UNION ALL SELECT 'YCWL','远成物流' FROM DUAL
UNION ALL SELECT 'YD','韵达快递' FROM DUAL
UNION ALL SELECT 'YDH','义达国际物流' FROM DUAL
UNION ALL SELECT 'YFEX','越丰物流' FROM DUAL
UNION ALL SELECT 'YFHEX','原飞航物流' FROM DUAL
UNION ALL SELECT 'YFSD','亚风快递' FROM DUAL
UNION ALL SELECT 'YTKD','运通快递' FROM DUAL
UNION ALL SELECT 'YTO','圆通速递' FROM DUAL
UNION ALL SELECT 'YXKD','亿翔快递' FROM DUAL
UNION ALL SELECT 'YZPY','邮政平邮/小包' FROM DUAL
UNION ALL SELECT 'ZENY','增益快递' FROM DUAL
UNION ALL SELECT 'ZHQKD','汇强快递' FROM DUAL
UNION ALL SELECT 'ZJS','宅急送' FROM DUAL
UNION ALL SELECT 'ZTE','众通快递' FROM DUAL
UNION ALL SELECT 'ZTKY','中铁快运' FROM DUAL
UNION ALL SELECT 'ZTO','中通速递' FROM DUAL
UNION ALL SELECT 'ZTWL','中铁物流' FROM DUAL
UNION ALL SELECT 'ZYWL','中邮物流' FROM DUAL
UNION ALL SELECT 'AMAZON','亚马逊物流' FROM DUAL
UNION ALL SELECT 'SUBIDA','速必达物流' FROM DUAL
UNION ALL SELECT 'RFEX','瑞丰速递' FROM DUAL
UNION ALL SELECT 'QUICK','快客快递' FROM DUAL
UNION ALL SELECT 'CJKD','城际快递' FROM DUAL
UNION ALL SELECT 'CNPEX','CNPEX中邮快递' FROM DUAL
UNION ALL SELECT 'HOTSCM','鸿桥供应链' FROM DUAL
UNION ALL SELECT 'HPTEX','海派通物流公司' FROM DUAL
UNION ALL SELECT 'AYCA','澳邮专线' FROM DUAL
UNION ALL SELECT 'PANEX','泛捷快递' FROM DUAL
UNION ALL SELECT 'PCA','PCA Express' FROM DUAL
UNION ALL SELECT 'UEQ','UEQ Express' FROM DUAL
;
COMMIT;

TRUNCATE TABLE M_BP_LOGISTIC;
INSERT INTO M_BP_LOGISTIC (BP_AN8,CODE,NAME)
SELECT 18026,'SF','顺丰快递' FROM DUAL
UNION ALL SELECT 18026,'YTO','圆通速递' FROM DUAL
UNION ALL SELECT 18026,'STO','申通快递' FROM DUAL
UNION ALL SELECT 18026,'ZTO','中通速递' FROM DUAL
UNION ALL SELECT 18030,'SF','顺丰快递' FROM DUAL
UNION ALL SELECT 18030,'YTO','圆通速递' FROM DUAL
UNION ALL SELECT 18030,'STO','申通快递' FROM DUAL
UNION ALL SELECT 18030,'ZTO','中通速递' FROM DUAL
UNION ALL SELECT 18030,'AMAZON','亚马逊物流' FROM DUAL
UNION ALL SELECT 18030,'FEDEX','FEDEX联邦(国内件）' FROM DUAL
UNION ALL SELECT 18030,'EMS','EMS' FROM DUAL
;
COMMIT;

