--DROP TABLE M_UDC_BASE;
CREATE TABLE M_UDC_BASE (
  JD number(6) DEFAULT null
, DOMAIN_CODE nchar(4) not null
, UDC_CODE nchar(2) not null
, VAL_CODE nchar(10) not null
, VAL_DESC nchar(30) DEFAULT null
, VAL_DESC2 nchar(30) DEFAULT null
, VAL_CODE2 nchar(10) DEFAULT null
, VAL_HARD nchar(1) DEFAULT null
, CONSTRAINT M_UDC_BASE_PK PRIMARY KEY (DOMAIN_CODE,UDC_CODE,VAL_CODE)
) NOLOGGING;
--INSERT INTO M_UDC_BASE SELECT * FROM S_M_UDC_BASE;

COMMENT ON TABLE M_UDC_BASE IS 'UDC';


--DROP TABLE M_UDC_DESC;
CREATE TABLE M_UDC_DESC (
  DOMAIN_CODE nchar(4) not null
, UDC_CODE nchar(2) not null
, VAL_CODE nchar(10) not null
, VAL_DESC nchar(30) DEFAULT null
, VAL_DESC2 nchar(30) DEFAULT null
, CONSTRAINT M_UDC_DESC_PK PRIMARY KEY (DOMAIN_CODE,UDC_CODE,VAL_CODE)
);

COMMENT ON TABLE M_UDC_DESC IS 'UDC额外描述';


--DROP TABLE M_UDC_META;
CREATE TABLE M_UDC_META (
  JD number(6) not null
, JT number(6) not null
, DOMAIN_CODE nchar(4) not null
, UDC_CODE nchar(2) not null
, VAL_SIZE number(2) not null
, CONSTRAINT M_UDC_META_PK PRIMARY KEY (DOMAIN_CODE,UDC_CODE)
) NOLOGGING;
--INSERT INTO M_UDC_META SELECT * FROM S_M_UDC_META;

COMMENT ON TABLE M_UDC_META IS 'UDC元数据';
COMMENT ON COLUMN M_UDC_META.VAL_SIZE IS 'UDC值宽度（小于10，则前空10-宽度）';


--DROP TABLE M_UDC_PAYMENT_TERM;
CREATE TABLE M_UDC_PAYMENT_TERM (
  JD number(6) DEFAULT null
, JT number(6) DEFAULT null
, VAL_CODE nchar(3) not null
, VAL_DESC nchar(30) DEFAULT null
, CONSTRAINT M_UDC_PAYMENT_TERM_PK PRIMARY KEY (VAL_CODE)
) NOLOGGING;
--INSERT INTO M_UDC_PAYMENT_TERM SELECT * FROM S_M_UDC_PAYMENT_TERM;

COMMENT ON TABLE M_UDC_PAYMENT_TERM IS 'UDC(月结客户的支付条款)';


--DROP TABLE M_CO;
CREATE TABLE M_CO (
  JD number(6) DEFAULT null
, JT number(6) DEFAULT null
, CODE nchar(5) not null
, NAME nchar(30) DEFAULT null
, CUR nchar(3) DEFAULT null
, CONSTRAINT M_CO_PK PRIMARY KEY (CODE)
) NOLOGGING;
--INSERT INTO M_CO SELECT * FROM S_M_CO;

COMMENT ON TABLE M_CO IS '公司主数据（00开头是总公司，18开头是分公司）';
COMMENT ON COLUMN M_CO.CODE IS '公司代码';
COMMENT ON COLUMN M_CO.NAME IS '公司名称';
COMMENT ON COLUMN M_CO.CUR IS '货币代码';


--DROP TABLE M_BP;
CREATE TABLE M_BP (
  JD number(6) DEFAULT null
, JT number(6) DEFAULT null
, AN8 number(8) not null
, CO_CODE nchar(5) DEFAULT null
, MCU_CODE nchar(12) DEFAULT null
, CODE nchar(10) DEFAULT null
, NAME nchar(40) DEFAULT null
, CONSTRAINT M_BP_PK PRIMARY KEY (AN8)
) NOLOGGING;
--INSERT INTO M_BP SELECT * FROM S_M_BP;

COMMENT ON TABLE M_BP IS '分公司主数据';
COMMENT ON COLUMN M_BP.AN8 IS 'BP号';
COMMENT ON COLUMN M_BP.CO_CODE IS '公司代码';
COMMENT ON COLUMN M_BP.MCU_CODE IS 'MCU代码';
COMMENT ON COLUMN M_BP.CODE IS 'BP代码';
COMMENT ON COLUMN M_BP.NAME IS 'BP名称';

CREATE UNIQUE INDEX M_BP_UI1 ON M_BP (CODE);


--DROP TABLE M_BP_MCU;
CREATE TABLE M_BP_MCU (
  JD number(6) DEFAULT null
, JT number(6) DEFAULT null
, AN8 number(8) DEFAULT null
, BP_CODE nchar(10) DEFAULT null
, CO_CODE nchar(5) DEFAULT null
, CODE nchar(12) not null
, NAME nchar(30) DEFAULT null
, ABBR nchar(40) DEFAULT null
, CONSTRAINT M_BP_MCU_PK PRIMARY KEY (AN8)
) NOLOGGING;
--INSERT INTO M_BP_MCU SELECT * FROM S_M_BP_MCU;

COMMENT ON TABLE M_BP_MCU IS '分公司仓库';
COMMENT ON COLUMN M_BP_MCU.AN8 IS '仓库号';
COMMENT ON COLUMN M_BP_MCU.BP_CODE IS 'BP代码';
COMMENT ON COLUMN M_BP_MCU.CO_CODE IS '公司代码';
COMMENT ON COLUMN M_BP_MCU.CODE IS '仓库代码';
COMMENT ON COLUMN M_BP_MCU.NAME IS '仓库名称';
COMMENT ON COLUMN M_BP_MCU.ABBR IS '仓库简称';

CREATE UNIQUE INDEX M_BP_MCU_UI1 ON M_BP_MCU (CODE);


--DROP TABLE M_BP_TEL;
CREATE TABLE M_BP_TEL (
  JD number(6) DEFAULT null
, JT number(6) DEFAULT null
, BP_AN8 number(8) not null
, SEQ number(3) not null
, TEL_AREA nchar(6) DEFAULT null
, TEL nchar(20) DEFAULT null
, CONSTRAINT M_BP_TEL_PK PRIMARY KEY (BP_AN8,SEQ)
) NOLOGGING;
--INSERT INTO M_BP_TEL SELECT * FROM S_M_BP_TEL;

COMMENT ON TABLE M_BP_TEL IS '分公司电话';
COMMENT ON COLUMN M_BP_TEL.BP_AN8 IS 'BP号';
COMMENT ON COLUMN M_BP_TEL.SEQ IS '显示顺序';
COMMENT ON COLUMN M_BP_TEL.TEL_AREA IS '电话区号';
COMMENT ON COLUMN M_BP_TEL.TEL IS '电话号码';


--DROP TABLE M_PG;
CREATE TABLE M_PG (
  ID number(18) not null
, PG nchar(8) not null
, CONSTRAINT M_PG_PK PRIMARY KEY (ID)
) NOLOGGING;
--INSERT INTO M_PG SELECT * FROM S_M_PG;

COMMENT ON TABLE M_PG IS '价格组';

CREATE UNIQUE INDEX M_PG_UI1 ON M_PG (PG);


--DROP TABLE M_ITEM;
CREATE TABLE M_ITEM (
  JD number(6) DEFAULT null
, NO number(8) not null
, CODE nchar(25) not null
, NAME nchar(30) DEFAULT null
, C1 nchar(3) DEFAULT null
, C2 nchar(3) DEFAULT null
, C3 nchar(3) DEFAULT null
, S1 nchar(3) DEFAULT null
, PG nchar(8) DEFAULT null
, LINE_TYPE nchar(2) DEFAULT null
, INV_STATUS nchar(1) DEFAULT null
, UOM nchar(2) DEFAULT null
, WOM nchar(2) DEFAULT null
, SPEC nchar(30) DEFAULT null
, MATERIAL nchar(6) DEFAULT null
, TEETH nchar(6) DEFAULT null
, BRAND nchar(30) DEFAULT null
, GRADE nchar(10) DEFAULT null
, TREAT nchar(30) DEFAULT null
, STD nchar(30) DEFAULT null
, DIM nchar(14) DEFAULT null
, DIM_VAL number(8) DEFAULT null
, LEN nchar(14) DEFAULT null
, LEN_VAL number(8) DEFAULT null
, CODE_OLD nchar(25) DEFAULT null
, CONSTRAINT M_ITEM_PK PRIMARY KEY (NO)
) NOLOGGING;
--INSERT INTO M_ITEM SELECT * FROM S_M_ITEM;

COMMENT ON TABLE M_ITEM IS '内销产品主数据';
COMMENT ON COLUMN M_ITEM.NO IS '产品号';
COMMENT ON COLUMN M_ITEM.CODE IS '产品代码';
COMMENT ON COLUMN M_ITEM.NAME IS '品名';
COMMENT ON COLUMN M_ITEM.C1 IS '料品总类';
COMMENT ON COLUMN M_ITEM.C2 IS '料品大类';
COMMENT ON COLUMN M_ITEM.C3 IS '料品货类';
COMMENT ON COLUMN M_ITEM.S1 IS 'UDC=41/S1';
COMMENT ON COLUMN M_ITEM.PG IS '价格组';
COMMENT ON COLUMN M_ITEM.LINE_TYPE IS '行类型(S=库存项目)';
COMMENT ON COLUMN M_ITEM.INV_STATUS IS '库存状态（O=已下架|U=已耗尽|...）';
COMMENT ON COLUMN M_ITEM.UOM IS '数量主计量单位';
COMMENT ON COLUMN M_ITEM.WOM IS '重量主计量单位';
COMMENT ON COLUMN M_ITEM.SPEC IS '规格';
COMMENT ON COLUMN M_ITEM.MATERIAL IS '材料';
COMMENT ON COLUMN M_ITEM.TEETH IS '牙别';
COMMENT ON COLUMN M_ITEM.BRAND IS '品牌';
COMMENT ON COLUMN M_ITEM.GRADE IS '等级';
COMMENT ON COLUMN M_ITEM.TREAT IS '表面处理';
COMMENT ON COLUMN M_ITEM.STD IS '标准';
COMMENT ON COLUMN M_ITEM.DIM IS '直径';
COMMENT ON COLUMN M_ITEM.DIM_VAL IS '直径值（mm）';
COMMENT ON COLUMN M_ITEM.LEN IS '长度';
COMMENT ON COLUMN M_ITEM.LEN_VAL IS '长度值（mm）';
COMMENT ON COLUMN M_ITEM.CODE_OLD IS '原来的产品代码';

CREATE UNIQUE INDEX M_ITEM_UI1 ON M_ITEM (CODE);


--DROP TABLE M_ITEM_EN;
CREATE TABLE M_ITEM_EN (
  JD number(6) DEFAULT null
, ITEM_NO number(8) not null
, NAME nchar(30) DEFAULT null
, CONSTRAINT M_ITEM_EN_PK PRIMARY KEY (ITEM_NO)
) NOLOGGING;
--INSERT INTO M_ITEM_EN SELECT * FROM S_M_ITEM_EN;

COMMENT ON TABLE M_ITEM_EN IS '产品英文名';
COMMENT ON COLUMN M_ITEM_EN.ITEM_NO IS '产品号';
COMMENT ON COLUMN M_ITEM_EN.NAME IS '英文名';


--DROP TABLE M_ITEM_UOM2KG;
CREATE TABLE M_ITEM_UOM2KG (
  JD number(6) DEFAULT null
, ITEM_NO number(8) not null
, KG_D7 number(18) DEFAULT null
, CONSTRAINT M_ITEM_UOM2KG_PK PRIMARY KEY (ITEM_NO)
) NOLOGGING;
--INSERT INTO M_ITEM_UOM2KG SELECT * FROM S_M_ITEM_UOM2KG;

COMMENT ON TABLE M_ITEM_UOM2KG IS '产品UOM重量';
COMMENT ON COLUMN M_ITEM_UOM2KG.ITEM_NO IS '产品号';
COMMENT ON COLUMN M_ITEM_UOM2KG.KG_D7 IS '主计量单位的重量（单位：KG/10^7）';


--DROP TABLE M_ITEM_XX2UOM;
CREATE TABLE M_ITEM_XX2UOM (
  JD number(6) DEFAULT null
, ITEM_NO number(8) not null
, UNIT nchar(2) not null
, CONV number(18) DEFAULT null
, CONSTRAINT M_ITEM_XX2UOM_PK PRIMARY KEY (ITEM_NO,UNIT)
) NOLOGGING;
--INSERT INTO M_ITEM_XX2UOM SELECT * FROM S_M_ITEM_XX2UOM;

COMMENT ON TABLE M_ITEM_XX2UOM IS '各种计量单位到UOM的数量转换矩阵';
COMMENT ON COLUMN M_ITEM_XX2UOM.ITEM_NO IS '产品号';
COMMENT ON COLUMN M_ITEM_XX2UOM.UNIT IS '计量单位（CA/BX）';
COMMENT ON COLUMN M_ITEM_XX2UOM.CONV IS '转换UOM的放大系数';


--DROP TABLE M_BASE_PRICE;
CREATE TABLE M_BASE_PRICE (
  JD number(6) DEFAULT null
, JT number(6) DEFAULT null
, ITEM_NO number(8) not null
, SINCE_JD number(6) not null
, UNTIL_JD number(6) not null
, PRICE_D4 number(18) DEFAULT null
, CONSTRAINT M_BASE_PRICE_PK PRIMARY KEY (ITEM_NO,SINCE_JD,UNTIL_JD)
) NOLOGGING;
--INSERT INTO M_BASE_PRICE SELECT * FROM S_M_BASE_PRICE;

COMMENT ON TABLE M_BASE_PRICE IS '面价主数据';
COMMENT ON COLUMN M_BASE_PRICE.ITEM_NO IS '产品号';
COMMENT ON COLUMN M_BASE_PRICE.SINCE_JD IS '起效日';
COMMENT ON COLUMN M_BASE_PRICE.UNTIL_JD IS '失效日';
COMMENT ON COLUMN M_BASE_PRICE.PRICE_D4 IS '价格（1/10^4）';


--DROP TABLE M_DISCOUNT;
CREATE TABLE M_DISCOUNT (
  JD number(6) not null
, JT number(6) not null
, CUST_AN8 number(8) not null
, MCU_CODE nchar(12) not null
, PG_ID number(18) not null
, ITEM_NO number(8) not null
, SINCE_JD number(6) not null
, UNTIL_JD number(6) not null
, DISC_D4 number(18) not null
) NOLOGGING;
--INSERT INTO M_DISCOUNT SELECT * FROM S_M_DISCOUNT;

COMMENT ON TABLE M_DISCOUNT IS '折扣主数据';
COMMENT ON COLUMN M_DISCOUNT.CUST_AN8 IS '客户号';
COMMENT ON COLUMN M_DISCOUNT.MCU_CODE IS '仓库代码';
COMMENT ON COLUMN M_DISCOUNT.PG_ID IS '价格组ID';
COMMENT ON COLUMN M_DISCOUNT.ITEM_NO IS '产品号';
COMMENT ON COLUMN M_DISCOUNT.SINCE_JD IS '起效日';
COMMENT ON COLUMN M_DISCOUNT.UNTIL_JD IS '失效日';
COMMENT ON COLUMN M_DISCOUNT.DISC_D4 IS '折扣（1/10^4）';

CREATE INDEX M_DISCOUNT_I1 ON M_DISCOUNT (CUST_AN8,MCU_CODE,PG_ID,SINCE_JD,UNTIL_JD);
CREATE INDEX M_DISCOUNT_I2 ON M_DISCOUNT (CUST_AN8,MCU_CODE,ITEM_NO,SINCE_JD,UNTIL_JD);
CREATE INDEX M_DISCOUNT_I3 ON M_DISCOUNT (MCU_CODE,PG_ID,SINCE_JD,UNTIL_JD);
CREATE INDEX M_DISCOUNT_I4 ON M_DISCOUNT (MCU_CODE,ITEM_NO,SINCE_JD,UNTIL_JD);


--DROP TABLE M_CUST;
CREATE TABLE M_CUST (
  JD number(6) DEFAULT null
, JT number(6) DEFAULT null
, AN8 number(8) not null
, SINCE_JD number(6) DEFAULT null
, UNTIL_JD number(6) DEFAULT null
, BP_AN8 number(8) DEFAULT null
, MCU_AN8 number(8) DEFAULT null
, EMP_AN8 number(8) DEFAULT null
, NAME nvarchar2(100) DEFAULT null
, CTG_CODE nchar(10) DEFAULT null
, SRC_CODE nchar(10) DEFAULT null
, LVL_CODE nchar(10) DEFAULT null
, STS_CODE nchar(10) DEFAULT null
, CREDIT_AMT number(18) DEFAULT null
, TERM_CODE varchar2(9) DEFAULT null
, C1 nchar(10) DEFAULT null
, C2 nchar(10) DEFAULT null
, C3 nchar(10) DEFAULT null
, INV_TYPE nchar(10) DEFAULT null
, INV_TITLE nvarchar2(100) DEFAULT null
, INV_TAXNO varchar2(100) DEFAULT null
, INV_BANK_NAME nvarchar2(100) DEFAULT null
, INV_BANK_ACCNO varchar2(60) DEFAULT null
, COMP_REG_ADDR nvarchar2(200) DEFAULT null
, COMP_REG_TEL varchar2(60) DEFAULT null
, INV_GTP_FLAG varchar2(3) DEFAULT null
, INV_VAT_FLAG varchar2(3) DEFAULT null
, ADDR_PROV nvarchar2(10) DEFAULT null
, ADDR_CITY nvarchar2(10) DEFAULT null
, ADDR_PREF nvarchar2(10) DEFAULT null
, ADDR_MORE nvarchar2(200) DEFAULT null
, PTC nvarchar2(20) DEFAULT null
, PHONE varchar2(60) DEFAULT null
, EMAIL varchar2(60) DEFAULT null
, TEL varchar2(60) DEFAULT null
, CONSTRAINT M_CUST_PK PRIMARY KEY (AN8)
) NOLOGGING;
--INSERT INTO M_CUST SELECT * FROM S_M_CUST;

COMMENT ON TABLE M_CUST IS '客户主数据';
COMMENT ON COLUMN M_CUST.AN8 IS '编号';
COMMENT ON COLUMN M_CUST.SINCE_JD IS '起效日';
COMMENT ON COLUMN M_CUST.UNTIL_JD IS '失效日';
COMMENT ON COLUMN M_CUST.BP_AN8 IS '对应的分公司';
COMMENT ON COLUMN M_CUST.MCU_AN8 IS '对应的出货仓库';
COMMENT ON COLUMN M_CUST.EMP_AN8 IS '对应的业务员';
COMMENT ON COLUMN M_CUST.NAME IS '名称';
COMMENT ON COLUMN M_CUST.CTG_CODE IS '类型';
COMMENT ON COLUMN M_CUST.SRC_CODE IS '来源';
COMMENT ON COLUMN M_CUST.LVL_CODE IS '等级';
COMMENT ON COLUMN M_CUST.STS_CODE IS '状态';
COMMENT ON COLUMN M_CUST.CREDIT_AMT IS '信用额度';
COMMENT ON COLUMN M_CUST.TERM_CODE IS '支付条款';
COMMENT ON COLUMN M_CUST.C1 IS '行业大类';
COMMENT ON COLUMN M_CUST.C2 IS '行业中类';
COMMENT ON COLUMN M_CUST.C3 IS '行业小类';
COMMENT ON COLUMN M_CUST.INV_TYPE IS '发票类型';
COMMENT ON COLUMN M_CUST.INV_TITLE IS '发票抬头';
COMMENT ON COLUMN M_CUST.INV_TAXNO IS '发票税号';
COMMENT ON COLUMN M_CUST.INV_BANK_NAME IS '开户银行';
COMMENT ON COLUMN M_CUST.INV_BANK_ACCNO IS '银行账户';
COMMENT ON COLUMN M_CUST.COMP_REG_ADDR IS '公司注册地址';
COMMENT ON COLUMN M_CUST.COMP_REG_TEL IS '公司注册电话';
COMMENT ON COLUMN M_CUST.INV_GTP_FLAG IS '一般纳税人？';
COMMENT ON COLUMN M_CUST.INV_VAT_FLAG IS '增值税发票？';
COMMENT ON COLUMN M_CUST.ADDR_PROV IS '地址：省';
COMMENT ON COLUMN M_CUST.ADDR_CITY IS '地址：市';
COMMENT ON COLUMN M_CUST.ADDR_PREF IS '地址：区';
COMMENT ON COLUMN M_CUST.ADDR_MORE IS '详细地址';
COMMENT ON COLUMN M_CUST.PTC IS '联系人';
COMMENT ON COLUMN M_CUST.PHONE IS '联系手机';
COMMENT ON COLUMN M_CUST.EMAIL IS '联系邮箱';
COMMENT ON COLUMN M_CUST.TEL IS '联系电话';


--DROP TABLE M_EMP;
CREATE TABLE M_EMP (
  JD number(6) DEFAULT null
, JT number(6) DEFAULT null
, AN8 number(8) not null
, BP_CODE nchar(10) DEFAULT null
, NAME nchar(40) DEFAULT null
, CONSTRAINT M_EMP_PK PRIMARY KEY (AN8)
) NOLOGGING;
--INSERT INTO M_EMP SELECT * FROM S_M_EMP;

COMMENT ON TABLE M_EMP IS '员工主数据';
COMMENT ON COLUMN M_EMP.AN8 IS '员工号';
COMMENT ON COLUMN M_EMP.BP_CODE IS '所属BP代码';
COMMENT ON COLUMN M_EMP.NAME IS '姓名';


--DROP TABLE M_BP_MCU_ITEM;
CREATE TABLE M_BP_MCU_ITEM (
  JD number(6) DEFAULT null
, JT number(6) DEFAULT null
, MCU_CODE nchar(12) not null
, ITEM_NO number(8) not null
, CONSTRAINT M_BP_MCU_ITEM_PK PRIMARY KEY (MCU_CODE,ITEM_NO)
) NOLOGGING;
--INSERT INTO M_BP_MCU_ITEM SELECT * FROM S_M_BP_MCU_ITEM;

COMMENT ON TABLE M_BP_MCU_ITEM IS '产品库存记录';
COMMENT ON COLUMN M_BP_MCU_ITEM.MCU_CODE IS '仓库号';
COMMENT ON COLUMN M_BP_MCU_ITEM.ITEM_NO IS '商品号';


--DROP TABLE M_LOGISTIC;
CREATE TABLE M_LOGISTIC (
  CODE varchar2(20) not null
, NAME nvarchar2(20) not null
, CONSTRAINT M_LOGISTIC_PK PRIMARY KEY (CODE)
);

COMMENT ON TABLE M_LOGISTIC IS '第三方物流主数据';
COMMENT ON COLUMN M_LOGISTIC.CODE IS '代码';
COMMENT ON COLUMN M_LOGISTIC.NAME IS '名称';


--DROP TABLE M_BP_LOGISTIC;
CREATE TABLE M_BP_LOGISTIC (
  BP_AN8 number(8) not null
, CODE varchar2(20) not null
, NAME nvarchar2(20) not null
, CONSTRAINT M_BP_LOGISTIC_PK PRIMARY KEY (BP_AN8,CODE)
);

COMMENT ON TABLE M_BP_LOGISTIC IS '分公司维护的第三方物流';
COMMENT ON COLUMN M_BP_LOGISTIC.BP_AN8 IS 'BP号';
COMMENT ON COLUMN M_BP_LOGISTIC.CODE IS '代码';
COMMENT ON COLUMN M_BP_LOGISTIC.NAME IS '名称';




