--DROP TABLE S_COUNTER;
CREATE TABLE S_COUNTER (
  COUNTER_CODE varchar2(20) not null
, COUNTER_DESC nvarchar2(200) not null
, COUNTER_KEY varchar2(20) not null
, COUNTER_MAX number(18) not null
, COUNTER_VAL number(18) not null
, CONSTRAINT S_COUNTER_PK PRIMARY KEY (COUNTER_CODE,COUNTER_KEY)
);

COMMENT ON TABLE S_COUNTER IS '发号器';
COMMENT ON COLUMN S_COUNTER.COUNTER_CODE IS '发号器编码';
COMMENT ON COLUMN S_COUNTER.COUNTER_DESC IS '发号器描述';
COMMENT ON COLUMN S_COUNTER.COUNTER_KEY IS '发号键';
COMMENT ON COLUMN S_COUNTER.COUNTER_MAX IS '最大流水号';
COMMENT ON COLUMN S_COUNTER.COUNTER_VAL IS '当前流水号';


--DROP TABLE S_MENU;
CREATE TABLE S_MENU (
  MENU_CODE varchar2(20) not null
, MENU_NAME nvarchar2(40) not null
, MENU_TYPE char(1) not null
, MENU_LVL number(1) not null
, MENU_SEQ number(3) not null
, MENU_URI varchar2(100) DEFAULT null
, MENU_API varchar2(100) DEFAULT null
, MENU_ICO varchar2(20) not null
, CONSTRAINT S_MENU_PK PRIMARY KEY (MENU_CODE)
);

COMMENT ON TABLE S_MENU IS '主菜单配置';
COMMENT ON COLUMN S_MENU.MENU_CODE IS '菜单码';
COMMENT ON COLUMN S_MENU.MENU_NAME IS '菜单名';
COMMENT ON COLUMN S_MENU.MENU_TYPE IS '菜单类型（M:菜单项、可见|C:配置项、不可见|X:禁用、不可见）';
COMMENT ON COLUMN S_MENU.MENU_LVL IS '菜单层级(一级菜单为1)';
COMMENT ON COLUMN S_MENU.MENU_SEQ IS '同级菜单显示顺序';
COMMENT ON COLUMN S_MENU.MENU_URI IS '画面前端路由';
COMMENT ON COLUMN S_MENU.MENU_API IS 'API访问路径(支持Ant路径表达式)';
COMMENT ON COLUMN S_MENU.MENU_ICO IS '菜单图标(fontawesome)';

CREATE UNIQUE INDEX S_MENU_UI1 ON S_MENU (MENU_URI);
CREATE UNIQUE INDEX S_MENU_UI2 ON S_MENU (MENU_API);


--DROP TABLE S_FUNC;
CREATE TABLE S_FUNC (
  MENU_CODE varchar2(20) not null
, FUNC_CODE varchar2(20) not null
, FUNC_NAME nvarchar2(40) not null
, FUNC_DESC nvarchar2(200) DEFAULT null
, FUNC_API varchar2(100) not null
, FUNC_TYPE char(1) not null
, CONSTRAINT S_FUNC_PK PRIMARY KEY (FUNC_CODE)
);

COMMENT ON TABLE S_FUNC IS '功能权限管控';
COMMENT ON COLUMN S_FUNC.MENU_CODE IS '菜单码';
COMMENT ON COLUMN S_FUNC.FUNC_CODE IS '功能码';
COMMENT ON COLUMN S_FUNC.FUNC_NAME IS '功能名';
COMMENT ON COLUMN S_FUNC.FUNC_DESC IS '详细描述';
COMMENT ON COLUMN S_FUNC.FUNC_API IS 'API或页面链接';
COMMENT ON COLUMN S_FUNC.FUNC_TYPE IS '配置类型（A:API|L:链接）';

CREATE UNIQUE INDEX S_FUNC_UI1 ON S_FUNC (FUNC_API);
CREATE UNIQUE INDEX S_FUNC_UI2 ON S_FUNC (FUNC_TYPE);


--DROP TABLE S_ROLE;
CREATE TABLE S_ROLE (
  ROLE_CODE varchar2(20) not null
, ROLE_NAME nvarchar2(40) not null
, ROLE_DESC nvarchar2(200) DEFAULT null
, ROLE_TYPE char(1) DEFAULT 'C'
, CONSTRAINT S_ROLE_PK PRIMARY KEY (ROLE_CODE)
);

COMMENT ON TABLE S_ROLE IS '角色';
COMMENT ON COLUMN S_ROLE.ROLE_CODE IS '角色码';
COMMENT ON COLUMN S_ROLE.ROLE_NAME IS '角色名';
COMMENT ON COLUMN S_ROLE.ROLE_DESC IS '角色描述';
COMMENT ON COLUMN S_ROLE.ROLE_TYPE IS '角色类型（B:基础角色|C:自定义角色）';


--DROP TABLE S_ROLE_MENU;
CREATE TABLE S_ROLE_MENU (
  ROLE_CODE varchar2(20) not null
, MENU_CODE varchar2(20) not null
, CONSTRAINT S_ROLE_MENU_PK PRIMARY KEY (ROLE_CODE,MENU_CODE)
);

COMMENT ON TABLE S_ROLE_MENU IS '角色菜单配置';
COMMENT ON COLUMN S_ROLE_MENU.ROLE_CODE IS '角色码';
COMMENT ON COLUMN S_ROLE_MENU.MENU_CODE IS '菜单码';


--DROP TABLE S_ROLE_FUNC;
CREATE TABLE S_ROLE_FUNC (
  ROLE_CODE varchar2(20) not null
, FUNC_CODE varchar2(20) not null
, CONSTRAINT S_ROLE_FUNC_PK PRIMARY KEY (ROLE_CODE,FUNC_CODE)
);

COMMENT ON TABLE S_ROLE_FUNC IS '角色功能配置';
COMMENT ON COLUMN S_ROLE_FUNC.ROLE_CODE IS '角色码';
COMMENT ON COLUMN S_ROLE_FUNC.FUNC_CODE IS '功能码';


--DROP TABLE S_DP_DEF;
CREATE TABLE S_DP_DEF (
  DP_CODE varchar2(20) not null
, DP_DESC nvarchar2(200) not null
, DP_OPEN char(1) DEFAULT '0'
, CONSTRAINT S_DP_DEF_PK PRIMARY KEY (DP_CODE)
);

COMMENT ON TABLE S_DP_DEF IS '数据权限定义';
COMMENT ON COLUMN S_DP_DEF.DP_CODE IS '配置编码';
COMMENT ON COLUMN S_DP_DEF.DP_DESC IS '配置描述';
COMMENT ON COLUMN S_DP_DEF.DP_OPEN IS '数据权限默认选项（Y:1=1|N:1<>1）';


--DROP TABLE S_DP_CFG;
CREATE TABLE S_DP_CFG (
  USER_TYPE varchar2(20) not null
, DP_CODE varchar2(20) not null
, DP_WAY varchar2(20) not null
, CONSTRAINT S_DP_CFG_PK PRIMARY KEY (USER_TYPE,DP_CODE)
);

COMMENT ON TABLE S_DP_CFG IS '数据权限配置';
COMMENT ON COLUMN S_DP_CFG.USER_TYPE IS '用户类型';
COMMENT ON COLUMN S_DP_CFG.DP_CODE IS '配置编码';
COMMENT ON COLUMN S_DP_CFG.DP_WAY IS '数据过滤方法(参考: DemoDpWay)';


--DROP TABLE S_MGMT_USER;
CREATE TABLE S_MGMT_USER (
  DELETED char(1) DEFAULT '0'
, UPDATED date DEFAULT sysdate
, ID number(18) not null
, EMAIL varchar2(60) not null
, PHONE varchar2(20) not null
, PASSWORD char(64) not null
, SALT char(16) not null
, USER_NAME nvarchar2(40) not null
, USER_TYPE char(1) not null
, EMP_AN8 number(8) DEFAULT null
, BP_AN8 number(8) DEFAULT null
, CONSTRAINT S_MGMT_USER_PK PRIMARY KEY (ID)
);

COMMENT ON TABLE S_MGMT_USER IS '管理用户';
COMMENT ON COLUMN S_MGMT_USER.EMAIL IS '邮箱（可用于登录）';
COMMENT ON COLUMN S_MGMT_USER.PHONE IS '电话（可用于登录）';
COMMENT ON COLUMN S_MGMT_USER.PASSWORD IS '登录密码（SHA256+SALT）';
COMMENT ON COLUMN S_MGMT_USER.SALT IS '密码的SALT';
COMMENT ON COLUMN S_MGMT_USER.USER_NAME IS '用户名（用于画面展示）';
COMMENT ON COLUMN S_MGMT_USER.USER_TYPE IS '用户类型（S:系统|H:总部|B:分公司）';
COMMENT ON COLUMN S_MGMT_USER.EMP_AN8 IS '员工号（S型用户为空）';
COMMENT ON COLUMN S_MGMT_USER.BP_AN8 IS '所属的分公司编号（B型用户不为空）';

CREATE UNIQUE INDEX S_MGMT_USER_UI1 ON S_MGMT_USER (EMAIL);
CREATE UNIQUE INDEX S_MGMT_USER_UI2 ON S_MGMT_USER (PHONE);

CREATE SEQUENCE SEQ_S_MGMT_USER MINVALUE 1 MAXVALUE 999999999999999999 CACHE 50;


--DROP TABLE S_MALL_USER;
CREATE TABLE S_MALL_USER (
  DELETED char(1) DEFAULT '0'
, UPDATED date DEFAULT sysdate
, ID number(18) not null
, EMAIL varchar2(60) not null
, PHONE varchar2(20) not null
, PASSWORD char(64) not null
, SALT char(16) not null
, USER_NAME nvarchar2(40) not null
, USER_TYPE char(1) not null
, CUST_AN8 number(8) DEFAULT null
, BP_AN8 number(8) DEFAULT null
, CONSTRAINT S_MALL_USER_PK PRIMARY KEY (ID)
);

COMMENT ON TABLE S_MALL_USER IS '商城用户';
COMMENT ON COLUMN S_MALL_USER.EMAIL IS '邮箱（可用于登录）';
COMMENT ON COLUMN S_MALL_USER.PHONE IS '电话（可用于登录）';
COMMENT ON COLUMN S_MALL_USER.PASSWORD IS '登录密码（SHA256+SALT）';
COMMENT ON COLUMN S_MALL_USER.SALT IS '密码的SALT';
COMMENT ON COLUMN S_MALL_USER.USER_NAME IS '用户名（用于画面展示）';
COMMENT ON COLUMN S_MALL_USER.USER_TYPE IS '用户类型（N:普通用户|C:建档客户）';
COMMENT ON COLUMN S_MALL_USER.CUST_AN8 IS '客户号';
COMMENT ON COLUMN S_MALL_USER.BP_AN8 IS '对应的的分公司编号';

CREATE UNIQUE INDEX S_MALL_USER_UI1 ON S_MALL_USER (EMAIL);
CREATE UNIQUE INDEX S_MALL_USER_UI2 ON S_MALL_USER (PHONE);

CREATE SEQUENCE SEQ_S_MALL_USER MINVALUE 1 MAXVALUE 999999999999999999 CACHE 50;


--DROP TABLE S_TRACE;
CREATE TABLE S_TRACE (
  ID number(18) not null
, LOGIN_NO varchar2(60) not null
, LOGIN_TIME date DEFAULT sysdate
, LOGOUT_TIME date DEFAULT null
, USER_ID number(18) not null
, CLIENT_IP char(15) not null
, CLIENT_UA varchar2(512) not null
, CONSTRAINT S_TRACE_PK PRIMARY KEY (ID)
);

COMMENT ON TABLE S_TRACE IS '用户访问审计';
COMMENT ON COLUMN S_TRACE.LOGIN_NO IS '登录号';
COMMENT ON COLUMN S_TRACE.LOGIN_TIME IS '登录时间';
COMMENT ON COLUMN S_TRACE.LOGOUT_TIME IS '登出时间';
COMMENT ON COLUMN S_TRACE.USER_ID IS '用户ID';
COMMENT ON COLUMN S_TRACE.CLIENT_IP IS '访问的客户端IP地址';
COMMENT ON COLUMN S_TRACE.CLIENT_UA IS '访问的浏览器环境信息';

CREATE SEQUENCE SEQ_S_TRACE MINVALUE 1 MAXVALUE 999999999999999999 CACHE 50;


--DROP TABLE S_TRACE_REQ;
CREATE TABLE S_TRACE_REQ (
  TRACE_ID number(18) not null
, REQ_URL varchar2(100) not null
, REQ_BEGIN date DEFAULT sysdate
, REQ_END date DEFAULT sysdate
, REQ_NODE varchar2(20) not null
);

COMMENT ON TABLE S_TRACE_REQ IS '用户请求审计';
COMMENT ON COLUMN S_TRACE_REQ.TRACE_ID IS 'S_TRACE.ID';
COMMENT ON COLUMN S_TRACE_REQ.REQ_URL IS '请求的URL';
COMMENT ON COLUMN S_TRACE_REQ.REQ_BEGIN IS '请求处理开始时间';
COMMENT ON COLUMN S_TRACE_REQ.REQ_END IS '请求处理结束时间';
COMMENT ON COLUMN S_TRACE_REQ.REQ_NODE IS '请求发生服务节点';


--DROP TABLE S_TRACE_OP;
CREATE TABLE S_TRACE_OP (
  TRACE_ID number(18) not null
, OP_TBL varchar2(20) not null
, OP_RID number(18) not null
, OP_CMD char(1) not null
, OP_TIME date DEFAULT sysdate
, OP_USER number(18) not null
);

COMMENT ON TABLE S_TRACE_OP IS '数据更新审计';
COMMENT ON COLUMN S_TRACE_OP.TRACE_ID IS 'S_TRACE.ID';
COMMENT ON COLUMN S_TRACE_OP.OP_TBL IS '数据表名';
COMMENT ON COLUMN S_TRACE_OP.OP_RID IS '数据记录ID';
COMMENT ON COLUMN S_TRACE_OP.OP_CMD IS '操作命令（C|U|X|D）';
COMMENT ON COLUMN S_TRACE_OP.OP_TIME IS '操作时间';
COMMENT ON COLUMN S_TRACE_OP.OP_USER IS '操作用户ID';


